cache: yarn

language: node_js
node_js:
  - "6.7"

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn test
  - yarn tsc
  - yarn run lint
  - yarn run danger

deploy:
  provider: script
  script: scripts/deploy_apphub.sh
  on:
    branch: master

cache:
  yarn: true
  directories:
    - node_modules
